version: 0.1
phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  baseDirectory: build
  files:
    - '**/*'
cache:
  paths:
    - node_modules/**/*
